// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuHeZp-EA5oMtkIYe4iU1NB4mc99kqt-A',
    appId: '1:758777300794:web:641e626eda8219ef893203',
    messagingSenderId: '758777300794',
    projectId: 'herohabit-app',
    authDomain: 'herohabit-app.firebaseapp.com',
    storageBucket: 'herohabit-app.firebasestorage.app',
    measurementId: 'G-VERPMLBY0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjW5eZCZVXLynepqldO-cIWmmtgqVY3sw',
    appId: '1:758777300794:android:b242130ef7aa7f2b893203',
    messagingSenderId: '758777300794',
    projectId: 'herohabit-app',
    storageBucket: 'herohabit-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9UDu9BxWBZQwUzJ0m35d2zT5bHU1oSis',
    appId: '1:758777300794:ios:1759da48e302da88893203',
    messagingSenderId: '758777300794',
    projectId: 'herohabit-app',
    storageBucket: 'herohabit-app.firebasestorage.app',
    iosBundleId: 'com.example.superHabit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9UDu9BxWBZQwUzJ0m35d2zT5bHU1oSis',
    appId: '1:758777300794:ios:1759da48e302da88893203',
    messagingSenderId: '758777300794',
    projectId: 'herohabit-app',
    storageBucket: 'herohabit-app.firebasestorage.app',
    iosBundleId: 'com.example.superHabit',
  );
}
